Create Foreword section and move content from Welcome page
the-turing-way/the-turing-way pull request #2080
Opened 2021-08-26 19:43 UTC by malvikasharan

### Summary

Fixes #2033 

* This PR creates a foreword section with project info, making welcome page light weight and easy to browse

### List of changes proposed in this PR (pull-request)

- [x] Revamp welcome page
- [x] Add foreword section with the following chapters
  - [x] Vision and Mission
  - [x] Background and History
  - [x] Navigating the book
  - [x] Community and Roles
  - [x] Ways of Working
  - [x] Impact
  - [x] Cite us

### What should a reviewer concentrate their feedback on?

- [ ] What other section should be added
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

2021-09-15 14:52 UTC, malvikasharan commented
@glimmerglen tagging you to this PR.

2022-06-27 12:26 UTC, aleesteele commented
Adding myself to this PR, as I'm reading through things with a few things in mind:
- How would a newcomer to the project interact with this page, and the phrasing therein?
- What information do different personas prioritise within the project?
- What is clear/unclear for these personas?

2022-10-14 13:59 UTC, aleesteele approved these changes
Adding comments for review in progress

2022-10-14 13:59 UTC, aleesteele commented on book/website/foreword/navigate.md
> +alt: The Turing Way Guide to reproducible research and it's stucture illustrated to show a set of doors to represent how it's built on chapters and sub chapters of the different areas of the guide
```suggestion
alt: The Turing Way Guide to reproducible research and its structure illustrated to show a set of doors to represent how it's built on chapters and sub chapters of the different areas of the guide
```

2022-10-14 13:59 UTC, aleesteele commented on book/website/foreword/impact.md
> +- _The Turing Way_ is also a flourishing global community of research engineers, data librarians, industry professionals and research experts dedicated to capturing and sharing research best-practise
```suggestion
- _The Turing Way_ is also a global community of research engineers, data librarians, industry professionals and research experts dedicated to capturing and sharing research best practices, tools and data for data science.  
```

2022-10-14 13:59 UTC, aleesteele commented on book/website/foreword/navigate.md
> +Each guides contain multiple chapters, and each chapters are divided into smaller, self-contained subchapters to allow you to naviagte the book and its content easily in your own pace
```suggestion
Each guides contain multiple chapters, and each chapters are divided into smaller, self-contained sub-chapters to allow you to navigate the book and its content easily in your own pace. Browse the different guides that make up the book, or use the search box to search for whatever you would like to learn about first. 

**Remember: _The Turing Way_ is not meant to be read from beginning to end!**
```

2022-10-17 15:12 UTC, aleesteele commented on book/website/foreword/foreword.md
> +- {ref}`Background and history<fw-background>`
```suggestion
- {ref}`Background and history<fw-history>`
```

2022-11-16 16:20 UTC, malvikasharan commented on book/website/welcome.md
> +_The Turing Way_ project receives support and funding from [The Alan Turing Institute](https://www.turing.ac.uk/) and is hosted under the [Tools, Practices and Systems programme](https://www.turing.a
```suggestion
Hosted under the [Tools, Practices and Systems Research Programme](https://www.turing.ac.uk/research/research-programmes/tools-practices-and-systems), _The Turing Way_ project receives support and funding from [The Alan Turing Institute](https://www.turing.ac.uk/) and is hosted under the [Tools, Practices and Systems programme](https://www.turing.ac.uk/research/research-programmes/tools-practices-and-systems) and co-led by **Drs. Kirstie Whitaker** and **Malvika Sharan**.
```

2023-06-06 20:21 UTC, aleesteele commented
Tied to #3159

2023-11-16 17:27 UTC, aleesteele commented
Bringing some of these into #3159 to start the forward section!

2024-02-26 19:40 UTC, aleesteele commented
Adding this here as a review for this foreword - will tackle this during the week of 26 Feb: https://docs.google.com/document/d/1Z_r0G6dmtlw0icQ_ctkhLG_QxZDhuRZaSTSkGvAVK6w/edit

2024-06-07 12:46 UTC, jessieontherun requested changes

2024-06-07 15:18 UTC, malvikasharan commented on book/website/foreword/community-roles.md
> +Researchers are also supported to lead community-based discussions and collaborations, that lead to projects and outputs beyond _The Turing Way_.
Integrated changes manually - thank you @jessieontherun.

2024-06-07 15:18 UTC, malvikasharan commented on book/website/foreword/community-roles.md
> +All members are supported to structure their work in _The Turing Way_ to make them findable and onboard new members in their work to provide continuity of their work.
Integrated changes manually - thank you @jessieontherun.

2024-06-07 15:18 UTC, malvikasharan commented on book/website/foreword/community-roles.md
> +* **Presenters and speakers** for international events/conferences who represent _The Turing Way_ in external platforms
Integrated changes manually - thank you @jessieontherun.

2024-06-07 15:18 UTC, malvikasharan commented on book/website/foreword/community-roles.md
> +* **Expert facilitators and trainers** of Open Science, Reproducibility and ethics-related workshops, both organised by _The Turing Way_ and delivered in external events
Integrated changes manually - thank you @jessieontherun.

2024-06-07 15:18 UTC, malvikasharan commented on book/website/welcome.md
> +For all processes and workflows for community participation and involvements, please see the {ref}`ch`.
Integrated changes manually - thank you @jessieontherun.

2024-06-07 15:19 UTC, malvikasharan commented on book/website/welcome.md
> +Our audience includes, but are not limited to, undergrad students, PhD researchers, postdocs, software engineers, Principle Investigators, project coordinators, community managers, data stewards, lib
Added that in the welcome page

2024-06-07 16:10 UTC, malvikasharan commented
Thank you @jessieontherun - Integrated the changes. I am going to merge this with a note that more people will review this. Exciting!!

2024-06-07 16:10 UTC, merged