Update README-Portuguese.md
the-turing-way/the-turing-way pull request #2116
Opened 2021-10-10 04:53 UTC by rafaelaqueirozg

### Summary
Update the README-Portuguese. Related to issue #2107 ([HACKTOBERFEST] README translated versions to update during HacktoberFest)

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: rafaelaqueirozg

2021-10-18 11:01 UTC, rafaelaqueirozg commented
@malvikasharan I would suggest @MarcosEllys

2021-11-11 22:09 UTC, malvikasharan commented
@all-contributors please add @MarcosEllys for translation, review

2021-11-11 22:10 UTC, malvikasharan commented
@all-contributors please add @rafaelaqueirozg  for tranlation, edit

2021-11-11 22:10 UTC, malvikasharan commented
@all-contributors please add @rafaelaqueirozg for translation, edit

2021-11-11 22:11 UTC, malvikasharan commented
@melibleq can you please suggest if the PR is ready to merge?

2022-08-01 17:52 UTC, malvikasharan commented
@AndreaSanchezTapia can I please ask for your help on this PR? 🙋🏽‍♀️

2023-08-19 01:10 UTC, melibleq requested changes
Hey! Re-reviewing this a while later. There are quite a lot of details that I changed. @AndreaSanchezTapia if you have some time would you mind taking a look? <3

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
> +Portanto, fornecemos vários pontos de entrada para você contribuir com base em seu interesse, disponibilidade ou requisitos de habilidade.
```suggestion
Por isso, fornecemos vários pontos de entrada para você contribuir com base em seu interesse, disponibilidade ou habilidades.
```

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
> +![Essa imagem mostra seis tipos de contribuições que todos podem fazer. São: desenvolver e compartilhar, manter e melhorar, compartilhar recursos, revisar e atualizar, torná-lo global por meio da tra
```suggestion
![Esta imagem mostra seis tipos de contribuições que todos podem fazer. São elas: desenvolver e compartilhar; manter e melhorar; compartilhar recursos; revisar e atualizar; globalizar por meio da tradução; e compartilhar as melhores práticas](book/website/figures/README_imgs/README_contributions.png)
```

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
> +*As contribuições incluem desenvolvimento e compartilhamento de novos capítulos; manutenção e melhoria dos capítulos existentes; compartilhamento de recursos do _The Turing Way_; revisão e atualizaçã
```suggestion
*As contribuições incluem desenvolvimento e compartilhamento de novos capítulos; manutenção e melhoria dos capítulos existentes; compartilhamento de recursos do _The Turing Way_; revisão e atualização de materiais desenvolvidos anteriormente; tradução de capítulos para ajudar a tornar este projeto globalmente acessível; e compartilhar as melhores práticas de pesquisa.*
```

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
> +Os membros da comunidade têm oportunidades de aprender novas habilidades, compartilhar suas ideias e colaborar com outros.
```suggestion
Pessoas membras da comunidade têm oportunidades de aprender novas habilidades, compartilhar suas ideias e colaborar com outras.
```

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
> +Eles também recebem oportunidades de mentoria no projeto à medida que fazem contribuições para _The Turing Way_ ou outros projetos de código aberto e são incentivados a serem mentores de novos partic
```suggestion
Elas também recebem oportunidades de mentoria no projeto à medida que fazem contribuições para _The Turing Way_ ou outros projetos de código aberto e são incentivadas a serem mentoras de novas pessoas que participem do projeto.
```

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
> +Nós criamos um [pacote promocional](https://github.com/alan-turing-institute/the-turing-way/tree/master/communications/promotion-pack) para ajudá-lo a apesentar e compartilhar sobre _The Turing Way_
```suggestion
Nós criamos um [pacote promocional](https://github.com/alan-turing-institute/the-turing-way/tree/master/communications/promotion-pack) para te ajudar a apesentar e compartilhar _The Turing Way_ nas suas redes.
```

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
>  Se você possuir alguma dúvida, [entre em contato](#entre-em-contato).
```suggestion
Se você tiver alguma dúvida, [entre em contato](#entre-em-contato).
```

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
>  As ilustrações do _The Turing Way_ são criadas por artistas da [Scriberia](https://www.scriberia.co.uk/) como parte do [_The Turing Way_ book dashes](https://github.com/alan-turing-institute/the-turi
```suggestion
As ilustrações do _The Turing Way_ são criadas por artistas da [Scriberia](https://www.scriberia.co.uk/) como parte dos eventos [_The Turing Way_ book dashes](https://github.com/alan-turing-institute/the-turing-way/tree/main/workshops/book-dash).  
```

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
>  Eles descrevem uma variedade de conteúdo do manual, esforços colaborativos na comunidade e o projeto _The Turing Way_ em geral.
```suggestion
Elas descrevem vários conteúdos do livro, os esforços colaborativos da comunidade e o projeto _The Turing Way_ em geral.
```

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
> +Conecte-se com outros e discuta suas ideias no Slack usando [esse link de convite](https://join.slack.com/t/theturingway/shared_invite/zt-fn608gvb-h_ZSpoA29cCdUwR~TIqpBw).
```suggestion
Conecte-se com outras pessoas e discuta suas ideias no Slack usando [este link de convite](https://join.slack.com/t/theturingway/shared_invite/zt-fn608gvb-h_ZSpoA29cCdUwR~TIqpBw).
```

2023-08-19 01:10 UTC, melibleq commented on README-translated/README-Portuguese.md
> +Nós também temos uma sala de chat no Gitter (se você prefere outra alternativa de código aberto para chat) e nós adoraríamos que você passasse para dizer "oi" em <https://gitter.im/alan-turing-instit
```suggestion
Nós também temos uma sala de chat no Gitter (se você prefere outra alternativa de código aberto para conversar) e adoraríamos que você passasse para dizer "oi" em <https://gitter.im/alan-turing-institute/the-turing-way>.
```

2025-09-10 15:39 UTC, closed without merging