Restructure table of contents
the-turing-way/the-turing-way pull request #3757
Opened 2024-06-11 08:06 UTC by JimMadge

### Summary

Simplify the table of contents structure by removing the unused parts section.
This shouldn't change the output, but does make the structure of the table of contents YAML easier to read.

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

2024-06-11 08:12 UTC, sgibson91 approved these changes

2024-06-11 19:53 UTC, bsipocz requested changes
Build failure is relevant as toc[parts] is being references. 

I leave the crossed out review to ensure this doesn't accidentally get merged before those references are cleaned up. 

Otherwise I'm 👍 for the PR.

2024-06-13 09:26 UTC, JimMadge commented
I've updated pathways and used a new commit hash so the build should be fixed now.

2024-06-13 17:46 UTC, bsipocz approved these changes

2024-06-13 17:46 UTC, merged