Software documentation chapter
the-turing-way/the-turing-way pull request #3768
Opened 2024-06-19 14:06 UTC by c-martinez

### Summary

This PR adds a new chapter on software documentation as part of the guide on reproducible research.

Fixes #879

### List of changes proposed in this PR (pull-request)

* Summary of the chapter 
* Section on code documentation
* Section on project documentation
* Section for other resources

### What should a reviewer concentrate their feedback on?
- [ ] Everything looks ok?
- [ ] How could this chapter be improved.
- [ ] Are there areas suggested in the issue #879 that are not yet covered

### Acknowledging contributors
- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file: 
@manuGil did most of the writing
@svenvanderburg, @paulmaxus and @JaroCamphuijsen contributed to the discussion.

2024-08-19 17:57 UTC, aleesteele commented
@all-contributors please add @manuGil for writing

2024-08-19 17:59 UTC, aleesteele commented
@all-contributors please add @manuGil for content

2024-11-06 19:02 UTC, EstherPlomp requested changes
Hi @c-martinez! I think this looks great - I just have some spelling things and internal referencing that need to be addressed and a suggested resource to add :)

2024-11-06 19:02 UTC, EstherPlomp commented on book/website/reproducible-research/code-documentation/code-documentation-project.md
> +and this [template](https://github.com/jessesquires/.github/blob/main/CODE_OF_CONDUCT.md) can be used as is or be adapted for a software project.
```suggestion
and this [template](https://github.com/jessesquires/.github/blob/main/CODE_OF_CONDUCT.md) can be used as is or be adapted for a software project.
See also the Turing Way's {ref}`ch-coc`.
```

2024-11-06 19:02 UTC, EstherPlomp commented on book/website/reproducible-research/code-documentation/code-documentation-resources.md
> +- Markdown
```suggestion
- Markdown
- How to document your research software[](https://coderefinery.github.io/documentation/#how-to-document-your-research-software) by CodeRefinery
```

2024-11-07 09:17 UTC, c-martinez commented on book/website/reproducible-research/code-documentation/code-documentation-resources.md
> +- Markdown
```suggestion
- [Markdown](https://daringfireball.net/projects/markdown/)
```

2024-11-07 09:18 UTC, c-martinez commented
Thanks @EstherPlomp -- I've incorporated your suggestions, so if you are happy with it, I guess we I can merge it later today :-)

2024-11-07 14:54 UTC, EstherPlomp approved these changes
Fantastic, thanks @c-martinez!

2024-11-07 21:09 UTC, merged