Add references to the bibliography and a cross reference in open source software
the-turing-way/the-turing-way pull request #3771
Opened 2024-06-23 15:19 UTC by RichardJActon

### Summary

Add 2 references mentioned in the text but not present in the bibliography to the bibliography, and add a cross reference to open source licensing chapter where it was mentioned here.

Addresses some points raised in #3705 

### List of changes proposed in this PR (pull-request)

* cross reference licensing chapter on first mention of 'open-source licence'
* Add reference to Gorgolewski et al 2016 to the bibliography
* Add reference to Pedregosa et al. 2012 to the bibliography

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.

2024-06-24 19:44 UTC, JimMadge requested changes
Looks good.

Assuming we can do without the abstracts and some other fields in the bibliography.

2024-06-24 19:44 UTC, JimMadge commented on book/website/_bibliography/references.bib
> +  langid = {english}
```suggestion
```

2024-06-24 19:44 UTC, JimMadge commented on book/website/_bibliography/references.bib
> +  abstract = {Scikit-learn is a Python module integrating a wide range of state-of-the-art machine learning algorithms for medium-scale supervised and unsupervised problems. This package focuses on b
```suggestion
```

2024-06-24 19:44 UTC, JimMadge commented on book/website/_bibliography/references.bib
> +  keywords = {FOS: Computer and information sciences,Machine Learning (cs.LG),Mathematical Software (cs.MS)}
```suggestion
```

2024-06-26 16:54 UTC, RichardJActon commented
Yes - thanks @JimMadge (just copy pasted from my reference manager's output and didn't think to remove the bloat)

2024-06-26 17:06 UTC, malvikasharan approved these changes

2024-06-27 09:29 UTC, JimMadge approved these changes

2024-06-27 09:30 UTC, merged