adding notes from community forum
the-turing-way/the-turing-way pull request #3788
Opened 2024-07-15 21:30 UTC by aleesteele

Hi folks! These are the archived notes from February, April, and July - reformatted slightly for clarity. Please let me know if I forgot anything.

2024-07-25 17:31 UTC, Arielle-Bennett requested changes
July notes are missing and several lines are incomplete so need reviewing against the recordings - also not clear if we made a call on sharing personal sign in data on GitHub - there was a convo with Data Protection but I can't remember what the outcome of that was?

2024-08-01 22:44 UTC, aleesteele commented on governance/community-calls/20240215-community-forum.md
> +Name / Organisation and location you are joining from / Social media (if you'd like to connect with others) /* *What's your favourite open source community (aside from The Turing Way, of course! 😉)?*
Thanks for reviewing this @Arielle-Bennett!

@KirstieJane's has said that her preference is to keep the introductions in all of our notes, as noted in #3553. After discussing this preference with Kit (who initially recommended that we drop introductions to just archive names), we are able to keep the introductions in if we note publicly that they will be archived.

2024-08-01 23:39 UTC, aleesteele commented on governance/community-calls/20240215-community-forum.md
> +    * LH/Accessibility WG: I invite anyone to participate in teh WG. Even if you think you don't know, you do. That learning can help everyone. I can hope that tinfrastructure WG that they could ask
Updated - closing this comment

2024-08-01 23:52 UTC, aleesteele commented on governance/community-calls/20240712-community-forum.md
> +
Closing as addressed above

2024-08-01 23:52 UTC, aleesteele commented on governance/community-calls/20240423-community-forum.md
> +*(Getting to know each other and this Etherpad for collaborative notes)*
Closing as addressed above

2024-08-02 00:04 UTC, aleesteele commented
Alright - edited and clarified notes, as well as updated July's notes too. Thanks so much for reviewing @Arielle-Bennett 🙏

2024-08-13 15:51 UTC, bsipocz commented
This has the commits from #3159 mixed in, and has also conflicts with `main`, so I go ahead for a cleaning mission and remove the unrelated content.

2024-08-29 14:25 UTC, aleesteele commented
Thank you so much @bsipocz! 🙏  I've been having issues with my pull requests recently - sorted through my commits in #3533 😆 It is much, much appreciated!

2024-08-29 15:40 UTC, bsipocz commented
Yes, sadly this doesn't teach you to rebase, but for practising I would recommend doing some of the exercises at https://learngitbranching.js.org

2024-10-21 05:58 UTC, malvikasharan commented
Those who have reviewed it, can we go ahead an merge it?
I have looked through and I don't think editing of the notes is needed - as we need these for archiving purpose.

2024-10-21 05:58 UTC, malvikasharan approved these changes

2024-10-21 05:59 UTC, merged