Update bookdash-selection.md
the-turing-way/the-turing-way pull request #3797
Opened 2024-08-05 00:32 UTC by aleesteele

### Summary

Discussing with @EstherPlomp of the @the-turing-way/book-dash-working-group - we thought this edit should be added to describe the responsibilities of being a part of the Book Dash Working group in a more binding way.

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

2024-08-05 05:46 UTC, EstherPlomp requested changes
Thanks Anne! I had a look and I think we need a couple more changes....

2024-08-05 05:46 UTC, EstherPlomp commented on book/website/community-handbook/bookdash/bookdash-selection.md
>  - **Planning Meeting**: attend a planning meeting to help select a date, agree on the format and share any feedback on the previous event that can help plan the Book Dash (time commitment: up to 30 m
```suggestion
- **Planning Meetings**: attend a planning meeting to help select a date, agree on the format and share any feedback on the previous event that can help plan the Book Dash (time commitment: up to 30-60 minutes in the months leading to the Book Dash)
```

2024-08-05 05:46 UTC, EstherPlomp commented on book/website/community-handbook/bookdash/bookdash-selection.md
>  - **Selection meeting**: participate in the selection meeting to help ensure that the selection is equitable (time commitment: 1.5-2 hours)
```suggestion
- **Selection meeting**: participate in the selection meeting to help ensure that the selection is equitable (time commitment: 60 minutes)
```

2024-08-05 19:50 UTC, aleesteele commented
Good catch, thanks @EstherPlomp! 🙏

2024-08-17 19:43 UTC, EstherPlomp approved these changes
Thanks Anne for the updates!

2024-08-21 14:42 UTC, aleesteele commented
Great, thanks @EstherPlomp !

2024-08-28 14:43 UTC, merged