[Ready for review] Update README-French.md to fix broken links
the-turing-way/the-turing-way pull request #3878
Opened 2024-10-30 19:00 UTC by nghuixin

- Fix broken links to all translated README.md
- Fix broken link to code of conduct
- Fix broken link to CONTRIBUTING.MD

### Summary

Fixes #<NUM>

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### List of changes proposed in this PR (pull-request)

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### What should a reviewer concentrate their feedback on?

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

2024-12-12 20:52 UTC, aleesteele commented
@annefou - maybe you could give this a review 😄 - Thinking of other folks who could give this look!

2024-12-14 14:56 UTC, annefou requested changes
The changes are correct.

But when I read the README (and not only the changes you made), I found:
- The link used for one image: Capture d'écran du livre en ligne The Turing Way ([utilisez cette image dans une présentation](https://drive.google.com/file/d/1wJR664YECSc8b_RSHeyVjDlHs-Ls9lkc/view?usp=sharing)) is broken;
- In the section "Citer les illustrations de _The Turing Way_ (en anglais)", the link to the image is broken (https://raw.githubusercontent.com/the-turing-way/the-turing-way/main/book/website/figures/evolution-open-research.jpg);
- The link https://github.com/the-turing-way/the-turing-way/tree/master/communications/promotion-pack does not exist (used in the sentence: Nous avons créé un [ensemble de promotion](https://github.com/the-turing-way/the-turing-way/tree/master/communications/promotion-pack) pour vous aider à présenter et à partager _The Turing Way_ dans votre réseau.)
- The link in the sentence "Pour voir comment nous procédons pour créer différentes versions, ou pour suggérer des améliorations, veuillez consulter ce [document de référence sur les versions](https://github.com/nghuixin/the-turing-way/blob/french-readme-update/README-translated/release-workflow.md)." is broken too.

2025-02-18 18:04 UTC, da5nsy approved these changes

2025-02-18 18:04 UTC, merged

2025-02-18 18:05 UTC, da5nsy commented
> The changes are correct.
> 
> But when I read the README (and not only the changes you made), I found:
> 
>     * The link used for one image: Capture d'écran du livre en ligne The Turing Way ([utilisez cette image dans une présentation](https://drive.google.com/file/d/1wJR664YECSc8b_RSHeyVjDlHs-Ls9lkc/view?usp=sharing)) is broken;
> 
>     * In the section "Citer les illustrations de _The Turing Way_ (en anglais)", the link to the image is broken (https://raw.githubusercontent.com/the-turing-way/the-turing-way/main/book/website/figures/evolution-open-research.jpg);
> 
>     * The link https://github.com/the-turing-way/the-turing-way/tree/master/communications/promotion-pack does not exist (used in the sentence: Nous avons créé un [ensemble de promotion](https://github.com/the-turing-way/the-turing-way/tree/master/communications/promotion-pack) pour vous aider à présenter et à partager _The Turing Way_ dans votre réseau.)
> 
>     * The link in the sentence "Pour voir comment nous procédons pour créer différentes versions, ou pour suggérer des améliorations, veuillez consulter ce [document de référence sur les versions](https://github.com/nghuixin/the-turing-way/blob/french-readme-update/README-translated/release-workflow.md)." is broken too.

Hi @annefou! 
Thanks for these points, would you be able to copy them into a new issue please (and a PR if you have capacity to start working on  them yourself)?

2025-02-18 18:08 UTC, da5nsy commented
Thanks @nghuixin! I've gone ahead and merged this! 🎉